spring:
  
  kafka:
    bootstrap-servers: ${PUBLIC_IP}:9092
    kafka.acks: all
    retries: 0
    consumer:
      auto-offset-reset: earliest
      group-id: customer-group      
    value.serializer: io.confluent.kafka.serializers.KafkaAvroSerializer
    schema-registry-url: http://${PUBLIC_IP}:8081

  jackson.serialization.indent_output: true
  
kafka:
  topic:
    customer: customer